In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/codeheroku/Introduction-to-Machine-Learning/master/Building%20a%20Movie%20Recommendation%20Engine/movie_dataset.csv")

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [14]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [15]:
features = ["keywords", "cast", "genres", "director"]

In [16]:
for i in features:
    df[i] = df[i].fillna('')

In [18]:
df.isna().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [19]:
df['combined_feature'] = df["keywords"] + " " + df["genres"] + " " + df["cast"] + " " + df["director"]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4803 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4803 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [21]:
df.head()

index  ...                                   combined_feature
0      0  ...  culture clash future space war space colony so...
1      1  ...  ocean drug abuse exotic island east india trad...
2      2  ...  spy based on novel secret agent sequel mi6 Act...
3      3  ...  dc comics crime fighter terrorist secret ident...
4      4  ...  based on novel mars medallion space travel pri...

[5 rows x 25 columns]

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [23]:
count_matrix = cv.fit_transform(df["combined_feature"])

In [26]:
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
from sklearn.metrics.pairwise import cosine_similarity

sim = cosine_similarity(count_matrix)

In [59]:
movie_user_likes = "The Notebook"

In [60]:
def get_index_from_title(name):
    return df[df.title == name]['index'].values[0]

In [61]:
def get_title_from_index(index):
    return df[df.index == index]['title'].values[0]

In [62]:
movie_index = get_index_from_title(movie_user_likes)

In [63]:
similar_movies = list(enumerate(sim[movie_index]))

In [64]:
sorted_similar_movies = sorted(similar_movies, key = lambda x: x[1], reverse=True)

In [65]:
i = 0
for movie in sorted_similar_movies[1:51]:
    print(get_title_from_index(movie[0]))

Two Lovers
Definitely, Maybe
Among Giants
The Fountain
Kate & Leopold
Rocky Balboa
Iris
Autumn in New York
A Beautiful Mind
Down to You
Return to Me
Wicker Park
Frida
Veer-Zaara
Spider-Man 3
Beyond Borders
My Best Friend's Wedding
The Crying Game
Cold Mountain
Spider-Man 2
The Good German
Crazy/Beautiful
Made of Honor
Me You and Five Bucks
The Story of Us
Mississippi Mermaid
You, Me and Dupree
Chasing Amy
Bedazzled
Once
Aloha
Mud
The Wedding Planner
Becoming Jane
Days of Heaven
Hope Floats
Lars and the Real Girl
The Ultimate Gift
Darling Companion
The Vow
Hancock
Shakespeare in Love
The Family Stone
Zack and Miri Make a Porno
Maurice
Gangster Squad
Blue Valentine
She's the One
How Do You Know
Jefferson in Paris
